# Generated by Django 5.2.3 on 2025-08-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('manage_properties', 'Can manage properties'), ('manage_tenants', 'Can manage tenants'), ('manage_leases', 'Can manage leases'), ('manage_payments', 'Can manage payments'), ('manage_maintenance', 'Can manage maintenance'), ('view_reports', 'Can view reports'), ('manage_users', 'Can manage users')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
    ]
