# Generated by Django 5.2.3 on 2025-08-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lease_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='reported_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_proof_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['property', 'tenant'], name='core_lease_propert_633a91_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date'], name='core_lease_start_d_0f902c_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='core_lease_end_dat_ae32c5_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['property', 'status'], name='core_mainte_propert_69d85f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['reported_date'], name='core_mainte_reporte_440848_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['lease', 'due_date'], name='core_paymen_lease_i_da28db_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'area'], name='core_proper_city_867014_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email'], name='core_tenant_email_789484_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone'], name='core_tenant_phone_cc945e_idx'),
        ),
    ]
