# Generated by Django 5.2.3 on 2025-08-04 10:21

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create groups
    property_manager_group, created = Group.objects.get_or_create(name='Property Manager')
    real_estate_agent_group, created = Group.objects.get_or_create(name='Real Estate Agent')
    admin_staff_group, created = Group.objects.get_or_create(name='Administrative Staff')
    finance_team_group, created = Group.objects.get_or_create(name='Finance Team')

    # Assign permissions
    property_permissions = Permission.objects.filter(content_type__app_label='core', content_type__model='property')
    tenant_permissions = Permission.objects.filter(content_type__app_label='core', content_type__model='tenant')
    lease_permissions = Permission.objects.filter(content_type__app_label='core', content_type__model='lease')
    payment_permissions = Permission.objects.filter(content_type__app_label='core', content_type__model='payment')
    maintenance_permissions = Permission.objects.filter(content_type__app_label='core', content_type__model='maintenancerequest')

    property_manager_group.permissions.add(*property_permissions)
    property_manager_group.permissions.add(*tenant_permissions)
    property_manager_group.permissions.add(*lease_permissions)
    property_manager_group.permissions.add(*payment_permissions)
    property_manager_group.permissions.add(*maintenance_permissions)

    real_estate_agent_group.permissions.add(*property_permissions.filter(codename__startswith='view'))

    admin_staff_group.permissions.add(*property_permissions.filter(codename__startswith='view'))
    admin_staff_group.permissions.add(*tenant_permissions.filter(codename__startswith='view'))

    finance_team_group.permissions.add(*payment_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lease_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]