# Generated by Django 5.2.3 on 2025-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='advanced_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
