# Generated by Django 5.2.3 on 2025-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_100k', 'Under $100,000'), ('100k_250k', '$100,000 - $250,000'), ('250k_500k', '$250,000 - $500,000'), ('500k_750k', '$500,000 - $750,000'), ('750k_1m', '$750,000 - $1,000,000'), ('over_1m', 'Over $1,000,000')], help_text='Estimated budget range of the lead', max_length=20, null=True, verbose_name='Budget Range'),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, help_text='Marketing campaign that generated this lead', max_length=100, verbose_name='Marketing Campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', help_text='Preferred method of contact', max_length=20, verbose_name='Preferred Contact Method'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level for follow-up', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Name of person who referred this lead', max_length=100, verbose_name='Referral Source'),
        ),
    ]
