# Generated by Django 5.2.3 on 2025-08-28 08:21

import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('income_proof', 'Income Proof'), ('reference', 'Reference Letter'), ('employment', 'Employment Verification'), ('other', 'Other Document')], max_length=20)),
                ('document', models.FileField(upload_to=apps.tenants.models.tenant_document_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
            ],
        ),
    ]
