# Generated by Django 5.2.3 on 2025-08-20 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.lease')),
            ],
            options={
                'indexes': [models.Index(fields=['lease', 'due_date'], name='payments_pa_lease_i_73c2f7_idx')],
            },
        ),
    ]
